# Generated by Django 4.0.3 on 2022-03-05 10:44

from django.db import migrations, models
import django.db.models.deletion
import filemgr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('is_explicit', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='content/files/')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ('-created', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FileSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protect_image', models.BooleanField(default=True, help_text="Hide image's url")),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_slider', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('is_explicit', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('file', models.ImageField(upload_to=filemgr.models.Image.get_path, verbose_name='Desktop Image Default')),
                ('m_file', models.ImageField(blank=True, null=True, upload_to=filemgr.models.Image.get_path, verbose_name='Mobile Image Default')),
                ('thumbnail', models.ImageField(max_length=500, null=True, upload_to=filemgr.models.Image.get_path, verbose_name='Desktop Thumbnail')),
                ('m_thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to=filemgr.models.Image.get_path, verbose_name='Mobile Thumbnail')),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('alt_text', models.CharField(blank=True, max_length=400)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('order', 'created'),
            },
            bases=(filemgr.models.BaseImage, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filemgr.image')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Supports HTML')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ('order', 'created'),
            },
            bases=('filemgr.image',),
        ),
    ]
