# Generated by Django 4.0.3 on 2022-03-05 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('source', models.CharField(blank=True, max_length=300, null=True)),
                ('medium', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('name', models.CharField(max_length=100, null=True)),
                ('path', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'User Path',
                'verbose_name_plural': 'User Paths',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TrackrSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_tracking_id', models.CharField(blank=True, help_text='Google Analytics Measurement ID', max_length=400, null=True, verbose_name='Google Analytics Tracking ID')),
                ('fb_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=400, null=True, verbose_name='Facebook Pixel ID')),
                ('filter_bot', models.BooleanField(default=True, verbose_name='Filter known bots traffic')),
                ('site', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='sites.site')),
            ],
            options={
                'verbose_name': 'Trackr Settings',
                'verbose_name_plural': 'Trackr Settings',
            },
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('count', models.PositiveIntegerField(default=0)),
                ('path', models.CharField(max_length=300)),
                ('referrer', models.TextField(default='')),
                ('session', models.CharField(max_length=100, null=True)),
                ('user_agent', models.TextField(default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='ip address')),
                ('q', models.CharField(blank=True, help_text='Google search query', max_length=300, null=True)),
                ('os', models.CharField(blank=True, max_length=300, null=True)),
                ('browser', models.CharField(blank=True, max_length=300, null=True)),
                ('is_mobile', models.BooleanField(default=False, verbose_name='is mobile')),
                ('is_bot', models.BooleanField(default=False, verbose_name='is bot')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hits', to='trackr.campaign')),
            ],
            options={
                'verbose_name': 'Hit',
                'verbose_name_plural': 'Hits',
                'ordering': ('-updated',),
            },
        ),
    ]
